import About from "./About/index";
import Carousel from "./Carousel/index";
import Content from "./Common/Content/index";
import Footer from "./Common/Footer/index";
import Header from "./Common/Header/index";
import Contact from "./Contact/index";
import NotFound from "./NotFound/index";
import Portfolio from "./Portfolio/index";
import Post from "./Post/index";

export { About };
export { Portfolio };
export { Post };
export { Carousel };
export { Contact };
export { Header };
export { Footer };
export { Content };
export { NotFound };
